export const FETCH_LAST_RELEASE_REQUEST = 'FETCH_LAST_RELEASE_REQUEST';
export const FETCH_LAST_RELEASE_SUCCESS = 'FETCH_LAST_RELEASE_SUCCESS';
export const FETCH_LAST_RELEASE_FAILURE = 'FETCH_LAST_RELEASE_FAILURE';

export const DETECT_USER_AGENT = 'DETECT_USER_AGENT';